name: Deploy client packet

on:
  push:
    tags: "contract-*"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Create the package
      run: dotnet pack --configuration Release src/Swisschain.GrpcLogger /p:Version=${GITHUB_REF#refs/tags/contract-}
    - name: Publish the package to GPR
      run: dotnet nuget push src/Swisschain.GrpcLogger/bin/Release/*.nupkg -s "https://api.nuget.org/v3/index.json" -k ${{ secrets.NUGET_TOCKEN }}
    - name: push gh
      run: dotnet nuget push src/Swisschain.GrpcLogger/bin/Release/*.nupkg --source "github"
