name: Deploy contract packet

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.100
        source-url: https://nuget.pkg.github.com/alexeynovichikhin/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.NUGET_TOCKEN}}
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Test with dotnet
      run: dotnet test --configuration Release
    - name: Create the package
      run: dotnet pack --configuration Release src/Swisschain.GrpcLogger.GrpcContracts
    - name: Publish the package to GPR
      run: dotnet nuget push src/Swisschain.GrpcLogger.GrpcContracts/bin/Release/*.nupkg
